// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQ_c808bjtpC5Sg300TUbX6HuuV4BYCg',
    appId: '1:320579719060:web:8ee8b973b857c6fdd34981',
    messagingSenderId: '320579719060',
    projectId: 'sogognouma-id-2',
    authDomain: 'sogognouma-id-2.firebaseapp.com',
    storageBucket: 'sogognouma-id-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArZ0Bmt8ccequwElgvzFSjopngT2mblow',
    appId: '1:320579719060:android:f083e4092670672ed34981',
    messagingSenderId: '320579719060',
    projectId: 'sogognouma-id-2',
    storageBucket: 'sogognouma-id-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzTIqgTjL1T1QwfkopavLyUo28uwosdUk',
    appId: '1:320579719060:ios:98845f10f643aad6d34981',
    messagingSenderId: '320579719060',
    projectId: 'sogognouma-id-2',
    storageBucket: 'sogognouma-id-2.appspot.com',
    iosBundleId: 'com.example.sogognouma',
  );
}
